# Generated by Django 5.2.15 on 2026-08-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_pokemon_appeared_at_pokemon_disappeared_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='appeared_at',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='disappeared_at',
        ),
    ]
