# Generated by Django 5.2.15 on 2026-08-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_alter_pokemonentity_lat_alter_pokemonentity_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default=None, upload_to='pokemon', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
