# Generated by Django 5.2.15 on 2026-08-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_alter_pokemon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_eng',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Имя на английском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_jpn',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Имя на японском'),
            preserve_default=False,
        ),
    ]
